import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Inter, Montserrat, Space_Grotesk } from "next/font/google";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"]
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Fenix",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} ${inter.variable} ${montserrat.variable} bg-default-blue text-light-white h-screen w-full antialiased`}
      >
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <Toaster
          position="bottom-center"
          toastOptions={{
            style: {
              background: "#2776D2",
              color: "white",
              border: "none"
            }
          }}
        />
      </body>
    </html>
  );
}
